// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrrBvqH7wI1LVNFgmdnsaxKYUfN0EYAiI',
    appId: '1:927030132497:web:9d970b9b51c70cd10916b0',
    messagingSenderId: '927030132497',
    projectId: 'geminichat-ee29d',
    authDomain: 'geminichat-ee29d.firebaseapp.com',
    storageBucket: 'geminichat-ee29d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK4C7CBiPvM18gp1Z88-2JFralcFQqwjY',
    appId: '1:927030132497:android:a168ae25a7f764520916b0',
    messagingSenderId: '927030132497',
    projectId: 'geminichat-ee29d',
    storageBucket: 'geminichat-ee29d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBb4IKNzWwMLvbOfeugkxO05IoDzmMEGIU',
    appId: '1:927030132497:ios:ef32b8a11e08ccbc0916b0',
    messagingSenderId: '927030132497',
    projectId: 'geminichat-ee29d',
    storageBucket: 'geminichat-ee29d.appspot.com',
    iosBundleId: 'com.example.gemini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBb4IKNzWwMLvbOfeugkxO05IoDzmMEGIU',
    appId: '1:927030132497:ios:7049e7209b5f73500916b0',
    messagingSenderId: '927030132497',
    projectId: 'geminichat-ee29d',
    storageBucket: 'geminichat-ee29d.appspot.com',
    iosBundleId: 'com.example.gemini.RunnerTests',
  );
}
